language: php
sudo: false

php:
  - 7.2

before_install:
  - rvm install 2.3
  - rvm use 2.3
  - gem install hiptest-publisher
  - "hiptest-publisher -c behat.conf --token=$SECRET_TOKEN --only=features,step_definitions --test-run-id=16135"
  - composer install

script:
  - vendor/bin/behat -f cucumber_json

after_script:
  - hiptest-publisher -c behat.conf --token=$SECRET_TOKEN --push=results/report.json --test-run-id=16135
